### ISSUE TITLE
idTokenを付けても認証が通らない

### ISSUE THREAD

**Issue by iridge-saito** [uskridge/cognito-local-sample#1]
aws-cli にて以下で確認

```shell
# ID_TOKEN="..." curl -H "Authorization: Bearer $ID_TOKEN" http://nest-cli:3000/api/ | jq
{
  "message": "Unauthorized",
  "statusCode": 401
}
```

moto-serverで以下のエラーが出ていた。
```
cognito   | Unable to find appropriate backend for ap-northeast-1.b82d37e9b34943bea83bd0b5b933b9ba.amazonaws.com.Remember to add the URL to urls.py, and run scripts/update_backend_index.py to index it.
cognito   | 172.21.0.4 - - [16/Apr/2024 10:17:02] "GET /ap-northeast-1_b82d37e9b34943bea83bd0b5b933b9ba/.well-known/jwks.json HTTP/1.1" 500 -
cognito   | Error on request:
cognito   | Traceback (most recent call last):
cognito   |   File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
cognito   |     execute(self.server.app)
cognito   |   File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
cognito   |     application_iter = app(environ, start_response)
cognito   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognito   |   File "/usr/local/lib/python3.11/site-packages/moto/moto_server/werkzeug_app.py", line 256, in __call__
cognito   |     backend_app = self.get_application(environ)
cognito   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognito   |   File "/usr/local/lib/python3.11/site-packages/moto/moto_server/werkzeug_app.py", line 195, in get_application
cognito   |     app = self.create_app(backend)
cognito   |           ^^^^^^^^^^^^^^^^^^^^^^^^
cognito   |   File "/usr/local/lib/python3.11/site-packages/moto/moto_server/werkzeug_app.py", line 278, in create_backend_app
cognito   |     backend_dict = backends.get_backend(service)
cognito   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cognito   |   File "/usr/local/lib/python3.11/site-packages/moto/backends.py", line 672, in get_backend
cognito   |     safe_name = name.replace("-", "")
cognito   |                 ^^^^^^^^^^^^^^^^^^^^^
cognito   | AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by iridge-saito** [comment]
以下、aws-cliコンテナからpublicKeyの取得をするコマンド。
[motoはURLだけではそれが idp 向けのリクエストか判断できないので、Authorization-header を付けなければいけない](https://docs.getmoto.org/en/latest/docs/services/cognito-idp.html#cognito-idp)らしい。

```shell
bash-4.2# curl http://cognito:9099/ap-northeast-1_805bc3e2ff2149b99524f71db3142f45/.well-known/jwks.json -H "Authorization: AWS4-HMAC-SHA256 Credential=mock_access_key/20220524/us-east-1/cognito-idp/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=asdf"
{
  "keys": [
    {
      "alg": "RS256",
      "e": "AQAB",
      "kid": "dummy",
      "kty": "RSA",
      "n": "j1pT3xKbswmMySvCefmiD3mfDaRFpZ9Y3Jl4fF0hMaCRVAt_e0yR7BeueDfqmj_NhVSO0WB5ao5e8V-9RFQOtK8SrqKl3i01-CyWYPICwybaGKhbJJR0S_6cZ8n5kscF1MjpIlsJcCzm-yKgTc3Mxk6KtrLoNgRvMwGLeHUXPkhS9YHfDKRe864iMFOK4df69brIYEICG2VLduh0hXYa0i-J3drwm7vxNdX7pVpCDu34qJtYoWq6CXt3Tzfi3YfWp8cFjGNbaDa3WnCd2IXpp0TFsFS-cEsw5rJjSl5OllJGeZKBtLeyVTy9PYwnk7MW43WSYeYstbk9NluX4H8Iuw",
      "use": "sig"
    }
  ]
}
```

これを Strategy でも再現する。
